# Generated by Django 5.0.2 on 2026-05-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehub_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero/Vendedor')], default='cajero', max_length=20),
        ),
    ]
